### ISSUE TITLE
Performance numbers for 3.11

### ISSUE THREAD

**Issue by markshannon** [plasma-umass/slipcover#17]
Not a bug, just a friendly request for more data :slightly_smiling_face: 

On https://pypi.org/project/slipcover/ you show a slowdown due to slipcover in the range 3% to 7%.
Does 3.11 show a similar slowdown?
And does this mean that tests run with slipcover on 3.11 outperform test without coverage on 3.10?

**Comment by jaltmayerpizzorno** [comment]
Hi Mark, sure!  I have partial results showing a 2% - 9% range, after adding a layer of abstraction (really needed it anyway, and made the port to 3.11 easier). It’s partial because I have had trouble building scikit-learn (or rather its dependencies) with 3.11, and thought it was easier to let their developers fix it.

I think it may be true, but don’t have a direct answer to your last question, sorry. I’m in Europe visiting family, back early July.  I’ll leave this issue open as a reminder to measure this and get back to you as soon as I can.

**Comment by jaltmayerpizzorno** [comment]
Hi Mark,

With the caveat that my benchmarking is still partial (I can build scikit-learn with 3.11.0b4 now, I just need to let it run, etc.), the answer is yes, 3.11 plus slipcover outperforms these benchmarks without coverage on 3.10:
```
bench            3.10.5    3.11.0b4 + slipcover
-------------  --------  ----------------------
mdp               10.89                   10.21
sudoku             8.19                    7.45
flask              7.88                    7.55
scimark            8.53                    6.53
spectral_norm      8.49                    6.58
raytrace          10                       6.11
```
