### ISSUE TITLE
XML report

### ISSUE THREAD

**Issue by slothyrulez** [plasma-umass/slipcover#6]
Hi, Can it be used to generate XML as [coverage.py](https://coverage.readthedocs.io/en/6.3.2/cmd.html#xml-reporting-coverage-xml) ?
Is planned ?

**Comment by jaltmayerpizzorno** [comment]
It can't right now, but thank you for suggesting it.  It hadn't been on our radar so far.

**Comment by exarkun** [comment]
I wanted to ingest slipcover measurements into coverage reporting services so I wrote a converter from slipcover output to coveralls.io format - https://github.com/PrivateStorageio/ZKAPAuthorizer/blob/8a447d2584b37eecef6fef97374293f16534c952/slipcover2coveralls.py

I think I might rather work with something like the xml format mentioned here though, since there are probably more tools for working on that than on the coveralls.io format.

Ideally, what form would support for this xml format take in slipcover?  Native support for directly emitting it?  A tool (like slipcover2coveralls.py) for post-processing slipcover's json format into the other format?

**Comment by adrinjalali** [comment]
Also considering this for a few projects, and it'd be awesome if we could do a plug and replacement and get the same kinda report which we can push to our backends.

**Comment by corentin-core** [comment]
Hello,
Any news on that? Particularly I would be interested in in `.xml` using Cobertura format in order to integrate it in our gitlab ci code coverage reporting:
https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscoverage_report
Is this kind of format planned to be supported?
Thanks
